#pragma once

#include <Vulkan/Core/VK_binding/Namespace.h>
#include <Vulkan/Core/VK_command/Namespace.h>
#include <Vulkan/Core/VK_data/Namespace.h>
#include <Vulkan/Core/VK_device/Namespace.h>
#include <Vulkan/Core/VK_drawer/Namespace.h>
#include <Vulkan/Core/VK_image/Namespace.h>
#include <Vulkan/Core/VK_instance/Namespace.h>
#include <Vulkan/Core/VK_memory/Namespace.h>
#include <Vulkan/Core/VK_pipeline/Namespace.h>
#include <Vulkan/Core/VK_pool/Namespace.h>
#include <Vulkan/Core/VK_presentation/Namespace.h>
#include <Vulkan/Core/VK_queue/Namespace.h>
#include <Vulkan/Core/VK_renderpass/Namespace.h>
#include <Vulkan/Core/VK_shader/Namespace.h>
#include <Vulkan/Core/VK_synchronization/Namespace.h>
#include <Vulkan/Core/VK_texture/Namespace.h>
#include <Vulkan/Core/VK_validation/Namespace.h>
#include <Vulkan/Core/Node.h>
#include <Vulkan/Core/Structure.h>
