[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pynephos"
version = "0.1"
description = "Vulkan Engine Python Bindings"
dependencies = []

[tool.setuptools.packages.find]
where = ["../../build/pynephos"]
include = ["*"]
