#pragma once

#include <Vulkan/Node.h>
#include <Vulkan/VK_queue/Namespace.h>
#include <Vulkan/VK_struct/Namespace.h>
#include <Vulkan/VK_binding/Namespace.h>
#include <Vulkan/VK_command/Namespace.h>
#include <Vulkan/VK_data/Namespace.h>
#include <Vulkan/VK_device/Namespace.h>
#include <Vulkan/VK_drawing/Namespace.h>
#include <Vulkan/VK_image/Namespace.h>
#include <Vulkan/VK_instance/Namespace.h>
#include <Vulkan/VK_gui/Namespace.h>
#include <Vulkan/VK_main/Namespace.h>
#include <Vulkan/VK_presentation/Namespace.h>
#include <Vulkan/VK_renderpass/Namespace.h>
#include <Vulkan/VK_shader/Namespace.h>
#include <Vulkan/VK_validation/Namespace.h>
#include <Vulkan/VK_render/Namespace.h>
#include <Vulkan/VK_synchronization/Namespace.h>
#include <Vulkan/VK_memory/Namespace.h>
#include <Vulkan/VK_pool/Namespace.h>
#include <Vulkan/VK_window/Namespace.h>
