#pragma once

#include <Vulkan/VK_struct/Struct_attachment.h>
#include <Vulkan/VK_struct/Struct_binding.h>
#include <Vulkan/VK_struct/Struct_buffer.h>
#include <Vulkan/VK_struct/Struct_command.h>
#include <Vulkan/VK_struct/Struct_image.h>
#include <Vulkan/VK_struct/Struct_object.h>
#include <Vulkan/VK_struct/Struct_data.h>
#include <Vulkan/VK_struct/Struct_physical_device.h>
#include <Vulkan/VK_struct/Struct_device.h>
#include <Vulkan/VK_struct/Struct_framebuffer.h>
#include <Vulkan/VK_struct/Struct_parameter.h>
#include <Vulkan/VK_struct/Struct_instance.h>
#include <Vulkan/VK_struct/Struct_pipeline.h>
#include <Vulkan/VK_struct/Struct_pool.h>
#include <Vulkan/VK_struct/Struct_subpass.h>
#include <Vulkan/VK_struct/Struct_renderpass.h>
#include <Vulkan/VK_struct/Struct_render.h>
#include <Vulkan/VK_struct/Struct_frame.h>
#include <Vulkan/VK_struct/Struct_swapchain.h>
#include <Vulkan/VK_struct/Struct_synchro.h>
#include <Vulkan/VK_struct/Struct_viewport.h>
#include <Vulkan/VK_struct/Struct_window.h>
#include <Vulkan/VK_struct/Struct_vulkan.h>
